localstack:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/localstack/localstack:0.14.3"
  environment:
    - SERVICES=sqs
  ports:
    - "4566:4566"
s3:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/localstack/localstack:0.14.3"
  environment:
    - SERVICES=s3
  ports:
    - "33333:4566"
