steps:
  - label: deploy to prod
    branches: "main"
    command: |
      ENV_TAG="env.prod" ./builds/update_ecr_image_tag.sh \
        uk.ac.wellcome/bag_register \
        uk.ac.wellcome/bag_replicator \
        uk.ac.wellcome/bag_root_finder \
        uk.ac.wellcome/bag_tagger \
        uk.ac.wellcome/bag_tracker \
        uk.ac.wellcome/bag_unpacker \
        uk.ac.wellcome/bag_verifier \
        uk.ac.wellcome/bag_versioner \
        uk.ac.wellcome/bags_api \
        uk.ac.wellcome/notifier \
        uk.ac.wellcome/replica_aggregator \
        uk.ac.wellcome/bag_indexer \
        uk.ac.wellcome/ingests_indexer \
        uk.ac.wellcome/ingests_api \
        uk.ac.wellcome/ingests_tracker \
        uk.ac.wellcome/ingests_worker \
        uk.ac.wellcome/file_finder \
        uk.ac.wellcome/file_indexer

      CLUSTER="storage-prod" ./builds/deploy_ecs_services.sh \
        storage-prod-bag-indexer \
        storage-prod-bag-replicator_azure \
        storage-prod-bag-replicator_glacier \
        storage-prod-bag-replicator_primary \
        storage-prod-bag-root-finder \
        storage-prod-bag-tagger \
        storage-prod-bag-unpacker \
        storage-prod-bag-verifier-pre-replication \
        storage-prod-bag-verifier_azure \
        storage-prod-bag-verifier_glacier \
        storage-prod-bag-verifier_primary \
        storage-prod-bag-versioner \
        storage-prod-bags-api \
        storage-prod-bag_register \
        storage-prod-file-finder \
        storage-prod-file-indexer \
        storage-prod-ingests-indexer \
        storage-prod-ingests-service \
        storage-prod-notifier \
        storage-prod-replica_aggregator

    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::975596993436:role/storage-ci"

    agents:
      queue: nano

  - wait

  - label: send a test bag in prod
    command:
      pip3 install --user boto3 wellcome_storage_service &&
      python3 .buildkite/scripts/send_and_wait_for_test_bag.py prod
    agents:
      queue: nano
