steps:
  - command: |
      ./builds/run_linting.sh
    label: "linting"
    agents:
      queue: "scala"

    # We increase the priority of this task because it may push a commit
    # and trigger a new build; if so, we want that to happen ASAP.
    priority: 1

  - label: "{{ matrix }} (library)"
    command: "./builds/run_sbt_tests.sh {{ matrix }}"
    matrix:
      - "common"
      - "display"
      - "indexer_common"

    agents:
      queue: "scala"

  - label: "{{ matrix }} (app)"
    command: |
      ./builds/run_sbt_tests.sh {{ matrix }}
      ./builds/build_sbt_image.sh {{ matrix }} "$BUILDKITE_COMMIT"

      if [[ "$BUILDKITE_BRANCH" == "main" ]]
      then
        ./builds/publish_sbt_image_to_ecr.sh {{ matrix }} "$BUILDKITE_COMMIT"
        ./builds/publish_image_to_ecr_public.sh {{ matrix }} "$BUILDKITE_COMMIT"
      fi

    matrix:
      - "bags_api"
      - "bag_register"
      - "bag_replicator"
      - "bag_root_finder"
      - "bag_tracker"
      - "bag_verifier"
      - "bag_unpacker"
      - "bag_versioner"
      - "replica_aggregator"
      - "bag_indexer"
      - "ingests_indexer"
      - "file_finder"
      - "file_indexer"
      - "ingests_worker"
      - "ingests_tracker"
      - "ingests_api"
      - "notifier"

    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::975596993436:role/storage-ci"

    agents:
      queue: "scala"

  - command:
      - cd scripts
      - python3 -m venv venv && source venv/bin/activate
      - pip3 install tox
      - venv/bin/tox -e py3
    label: "Test Python scripts"

  - wait

  - label: trigger stage deploy
    branches: "main"
    trigger: "storage-service-deploy-stage"
    async: true
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
        BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
        BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
