steps:
  - block: ":rocket: Deploy to prod?"
    prompt: "Deploying ref.$BUILDKITE_COMMIT: Are you happy to release this commit?"

  - label: deploy to prod
    plugins:
      - ecr#v2.1.1:
          login: true
          account_ids: "760097843905"
          assume_role:
            role_arn: "arn:aws:iam::760097843905:role/platform-ci"
      - docker#v3.5.0:
          image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/wellcome/weco-deploy:5.7"
          workdir: /repo
          mount-ssh-agent: true
          command: [
              "--confirm",
              "release-deploy",
              "--from-label", "latest",
              "--environment-id", "prod",
              "--description", $BUILDKITE_BUILD_URL,
              "--confirmation-wait-for", 3600]
    agents:
      queue: nano

  - wait

  - label: send a test bag in prod
    command:
      pip3 install --user boto3 wellcome_storage_service &&
      python3 .buildkite/scripts/send_and_wait_for_test_bag.py prod
    agents:
      queue: nano
