steps:
  - label: deploy to stage
    branches: "main"
    command: |
      ENV_TAG="env.stage" ./builds/update_ecr_image_tag.sh \
        uk.ac.wellcome/bag_register \
        uk.ac.wellcome/bag_replicator \
        uk.ac.wellcome/bag_root_finder \
        uk.ac.wellcome/bag_tagger \
        uk.ac.wellcome/bag_tracker \
        uk.ac.wellcome/bag_unpacker \
        uk.ac.wellcome/bag_verifier \
        uk.ac.wellcome/bag_versioner \
        uk.ac.wellcome/bags_api \
        uk.ac.wellcome/notifier \
        uk.ac.wellcome/replica_aggregator \
        uk.ac.wellcome/bag_indexer \
        uk.ac.wellcome/ingests_indexer \
        uk.ac.wellcome/ingests_api \
        uk.ac.wellcome/ingests_tracker \
        uk.ac.wellcome/ingests_worker \
        uk.ac.wellcome/file_finder \
        uk.ac.wellcome/file_indexer

      CLUSTER="storage-staging" ./builds/deploy_ecs_services.sh \
        storage-staging-bag-indexer \
        storage-staging-bag-replicator_azure \
        storage-staging-bag-replicator_glacier \
        storage-staging-bag-replicator_primary \
        storage-staging-bag-root-finder \
        storage-staging-bag-tagger \
        storage-staging-bag-unpacker \
        storage-staging-bag-verifier-pre-replication \
        storage-staging-bag-verifier_azure \
        storage-staging-bag-verifier_glacier \
        storage-staging-bag-verifier_primary \
        storage-staging-bag-versioner \
        storage-staging-bags-api \
        storage-staging-bag_register \
        storage-staging-file-finder \
        storage-staging-file-indexer \
        storage-staging-ingests-indexer \
        storage-staging-ingests-service \
        storage-staging-notifier \
        storage-staging-replica_aggregator

    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::975596993436:role/storage-ci"

    agents:
      queue: nano

  - wait

  - label: send a test bag in stage
    command:
      pip3 install --user boto3 wellcome_storage_service &&
      python3 .buildkite/scripts/send_and_wait_for_test_bag.py stage
    agents:
      queue: nano

  - wait

  - label: trigger prod deploy
    trigger: "storage-service-deploy-prod"
    async: true
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
        BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
        BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
