include makefiles/functions.Makefile

PROJECT_ID = storage

STACK_ROOT 	= indexer

SBT_APPS = bag_indexer file_finder file_indexer ingests_indexer
SBT_NO_DOCKER_APPS =

SBT_DOCKER_LIBRARIES    = indexer_common
SBT_NO_DOCKER_LIBRARIES =

LAMBDAS 	=

$(val $(call stack_setup))