include makefiles/functions.Makefile

PROJECT_ID = storage

STACK_ROOT 	= indexer

SBT_APPS =
SBT_NO_DOCKER_APPS =

SBT_DOCKER_LIBRARIES    = indexer_common
SBT_NO_DOCKER_LIBRARIES =

PYTHON_APPS =
LAMBDAS 	=

TF_NAME =
TF_PATH =

$(val $(call stack_setup))