localstack:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/localstack/localstack:0.14.2"
  environment:
    - SERVICES=sqs
  ports:
    - "4566:4566"
s3:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/localstack/localstack:0.14.2"
  environment:
    - SERVICES=s3
  ports:
    - "33333:4566"
azurite:
  image: "mcr.microsoft.com/azure-storage/azurite"
  ports:
    - "10000:10000"
  command: ["azurite", "--blobHost", "0.0.0.0"]
dynamodb:
  image: "public.ecr.aws/aws-dynamodb-local/aws-dynamodb-local"
  ports:
    - "45678:8000"
