version: "2.1"
services:
  localstack:
    image: "public.ecr.aws/localstack/localstack:3.0.0"
    environment:
      - SERVICES=sqs
      - ALLOW_NONSTANDARD_REGIONS=1
    ports:
      - "4566:4566"
  s3:
    image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/zenko/cloudserver:8.1.8"
    environment:
      - "S3BACKEND=mem"
    ports:
      - "33333:8000"
  azurite:
    image: "mcr.microsoft.com/azure-storage/azurite"
    ports:
      - "10000:10000"
    command: ["azurite", "--blobHost", "0.0.0.0"]
  dynamodb:
    image: "public.ecr.aws/aws-dynamodb-local/aws-dynamodb-local"
    ports:
      - "45678:8000"
