locals {
  bags_api_service_name    = "${var.namespace}-bags-api"
  ingests_service_name     = "${var.namespace}-ingests"
  ingests_api_service_name = "${var.namespace}-ingests-api"
  notifier_service_name    = "${var.namespace}-notifier"
  bagger_service_name      = "${var.namespace}-bagger"

  logstash_transit_service_name = "${var.namespace}-logstash-transit"
  logstash_transit_image        = "docker.elastic.co/logstash/logstash:7.2.0"

  bag_unpacker_service_name           = "${var.namespace}-bag-unpacker"
  bag_root_finder_service_name        = "${var.namespace}-bag-root-finder"
  bag_auditor_service_name            = "${var.namespace}-bag-auditor"
  bag_replicator_service_name         = "${var.namespace}-bag-replicator"
  bag_register_service_name           = "${var.namespace}-bag-register"
  bag_verifier_post_repl_service_name = "${var.namespace}-bag-verifier-post-replication"
  bag_verifier_pre_repl_service_name  = "${var.namespace}-bag-verifier-pre-replication"

  bag_auditor_image     = "${module.images.services["bag_auditor"]}"
  bag_register_image    = "${module.images.services["bag_register"]}"
  bag_root_finder_image = "${module.images.services["bag_root_finder"]}"
  bags_api_image        = "${module.images.services["bags_api"]}"
  ingests_image         = "${module.images.services["ingests"]}"
  ingests_api_image     = "${module.images.services["ingests_api"]}"
  notifier_image        = "${module.images.services["notifier"]}"
  bagger_image          = "${module.images.services["bagger"]}"
  bag_replicator_image  = "${module.images.services["bag_replicator"]}"
  bag_verifier_image    = "${module.images.services["bag_verifier"]}"
  bag_unpacker_image    = "${module.images.services["bag_unpacker"]}"
}
