s3:
  image: "zenko/cloudserver:8.1.8"
  environment:
    - "S3BACKEND=mem"
  ports:
    - "33333:8000"
dynamodb:
  image: peopleperhour/dynamodb
  ports:
    - "45678:8000"
sns:
  image: wellcome/fake-sns
  ports:
    - "9292:9292"
