include makefiles/functions.Makefile

PROJECT_ID = storage

STACK_ROOT 	= api

SBT_APPS = ingests_api \
           bags_api


SBT_DOCKER_LIBRARIES    =
SBT_NO_DOCKER_LIBRARIES =

PYTHON_APPS =
LAMBDAS 	=

TF_NAME =
TF_PATH =

$(val $(call stack_setup))