# Runs auto-formatting script on push to any branch
name: "Scala auto-formatting"

on: push

jobs:
  autoformat:
    uses: wellcomecollection/.github/.github/workflows/scala_formatting.yml@main
    permissions:
      id-token: write
      contents: write
    secrets:
      GHA_SCALA_FORMATTING_ROLE_ARN: ${{ secrets.GHA_SCALA_FORMATTING_ROLE_ARN }}
