name: Update Dependency Graph
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  dependency-graph:
    uses: wellcomecollection/.github/.github/workflows/dependency_graph.yml@main
    secrets: inherit