name: Deploy Ingest Inspector
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy_ingest_inspector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-lambda-zip
        with:
          folder: monitoring/ingest_inspector/backend_lambda
          upload_to_s3: "true"
          s3_bucket: wellcomecollection-storage-infra
          s3_key: lambdas/monitoring/ingest_inspector_backend.zip
          role_to_assume: ${{ secrets.DEPLOY_INGEST_INSPECTOR_GHA_ROLE_ARN }}
      - uses: ./.github/actions/deploy-lambda-zip
        with:
          lambda_name: ingest_inspector_backend
          s3_bucket: wellcomecollection-storage-infra
          s3_key: lambdas/monitoring/ingest_inspector_backend.zip
          role_to_assume: ${{ secrets.DEPLOY_INGEST_INSPECTOR_GHA_ROLE_ARN }}
      - name: Deploy Ingest Inspector frontend
        run: |
          cd monitoring/ingest_inspector/frontend
          sh deploy.sh
