name: Deploy Daily Reporter
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - rk/uv-monitoring-lambdas

permissions:
  id-token: write
  contents: read

jobs:
  deploy_daily_reporter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-lambda-zip
        with:
          folder: monitoring/daily_reporter
          upload_to_s3: "true"
          s3_bucket: wellcomecollection-storage-infra
          s3_key: lambdas/monitoring/daily_reporter.zip
          role_to_assume: ${{ secrets.DEPLOY_INGEST_INSPECTOR_GHA_ROLE_ARN }}
      - uses: ./.github/actions/deploy-lambda-zip
        with:
          lambda_name: daily_reporter
          s3_bucket: wellcomecollection-storage-infra
          s3_key: lambdas/monitoring/daily_reporter.zip
          role_to_assume: ${{ secrets.DEPLOY_INGEST_INSPECTOR_GHA_ROLE_ARN }}
